---
title: "Week 6 Homework: Palmers Penguins in Quarto"
author: "Mei Iwamoto"
format: 
  html: 
    code-fold: true              # code hidden by default, with a toggle button
    code-summary: "Show code"    # customize the button label
editor: visual
execute:
  warning: false   # suppress warnings in all chunks
  message: false   # suppress package loading messages
  eval: true       # run all chunks (the default)
---

```{r}
#load libaries
library(tidyverse)
library(here)
library(palmerpenguins)
library(kableExtra)
library(ggthemr)

#set theme for future plots using ggthemr package
ggthemr("dust")
```

## Creating a plot using the penguins data in Quarto

```{r}
#| label: fig-penguin-mass
#| fig-cap: "Body Mass of Adelie, Chinstrap, and Gentoo Penguins collected from 2007-2009."


#create plot showing body mass of the three penguin species to add to quarto doc
ggplot(penguins,
       mapping = aes(x=species, y=body_mass_g)) +
  geom_boxplot() +
  labs(title = "Body Mass of Adelie, Chinstrap, and Gentoo Penguins", x="Species", y="Body Mass (grams)") 

#save plot to outputs folder
#ggsave(here("Week_06", "Outputs", "HW_plot.png")) I was having error messages when trying to publish to Posit so I put the # for now
```

#### Cross referencing the plot in the prose
The body masses measured of the three different penguin species 

  - **Adelie**
  - **Chinstrap**
  - **Gentoo** 
  
are shown here in @fig-penguin-mass.


## Creating a table using the *kbl* function in Quarto
```{r}
#| label: tbl-adelie-body
#| tbl-cap: Mean body mass in grams of Adelie penguins from 2007 to 2009


#create table showing mean body mass of Adelie penguins over the years
penguins |> 
  filter(species=="Adelie") |> 
  group_by(year, sex) |> 
  summarise(mean_body_mass=mean(body_mass_g)) |>
  kbl() #use kbl function here 

```

Mean body mass of Adelie penguins from 2007-2009 are summarized here in @tbl-adelie-body.
